### ISSUE TITLE
Do not move cards on restack.

### ISSUE THREAD

**Issue by NBKRedSpy** [benediktwerner/Stacklands-BetterMouseControls-Mod#1]
Currently clicking the bottom most card of a stack will move the stack to the mouse pointer.  

It would be nice if the stack would stay at the same location.

Alternatively, could change the click to support clicking the top most card to mean "pull in cards, but don't move stack".

An easy way to see how the current functionally moves the cards is to take a stack of four or more and double click the last card.  The top of the stack will be moved to the previous location of the clicked card.

**Comment by NBKRedSpy** [comment]
Workaround:  
A workaround is to use CardZones.  Any card in a card zone won't reposition after merge.

https://stacklands.thunderstore.io/package/MSchmoecker/CardZones/

**Comment by benediktwerner** [comment]
It's intended like this so that you can continue to drag the new stack afterwards. I guess I can allow clicking on the top card though.
