### ISSUE TITLE
Disabling one function in game disables all.

### ISSUE THREAD

**Issue by NBKRedSpy** [benediktwerner/Stacklands-BetterMouseControls-Mod#3]
# Reproduction 

- Load into a game with both functions enabled.
- Go back to the mod's options and disable one of the functions.
- Load back into the game

Expected:  The enabled functions work.
Actual: Neither functions will work.

# Reason
The unpatch actually unpatches all if there isn't an id for the Harmony instance.  It's an oddity with Harmony that still isn't addressed.

Here's the fix I used previously.
Existing Code:

    harmony = Harmony.CreateAndPatchAll(patches);

Change:

    harmony = Harmony.CreateAndPatchAll(patches, patches.ToString());

**Comment by benediktwerner** [comment]
Thanks, fixed.
